config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htm
  root to: "cocktails#index"

  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [ :new, :create, :delete]

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, :uniqueness => true

  has_many :doses
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
   has_many :doses
   validates :name, presence: true, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
     @cocktail = Cocktail.new(cocktail_params)
      if @cocktail.save
        redirect_to @cocktail
      else
        render :new
      end
  end

  def edit
  end

  def update
  end

  def delete
    @cocktail.destroy
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def show
    @dose = Dose.find(params[:id])
  end

  def new
     @cocktail = Cocktail.find(params[:cocktail_id])
     @dose = Dose.new
  end

  def create
      @cocktail = Cocktail.find(params[:cocktail_id])
      @dose = Dose.new(doses_params)
      @dose.cocktail = @cocktail

      if @dose.save
        redirect_to @cocktail
      else
        render :new
    end
  end

  def edit
  end

  def update
  end

  def delete
    @dose = Dose.destroy
  end

  private

    def doses_params
      params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/delete.html.erb
<h1>Cocktails#delete</h1>
<p>Find me in app/views/cocktails/delete.html.erb</p>

app/views/cocktails/edit.html.erb
<h1>Cocktails#edit</h1>
<p>Find me in app/views/cocktails/edit.html.erb</p>

app/views/cocktails/index.html.erb
<div">
  <h1>Tiwong Restaurant!!!!!!!!!</h1>

  <h2>Social distancing in-place</h2>

<ul>
  <% @cocktails.each do |cocktail| %>
  <li><%= link_to cocktail.name, cocktail_path(cocktail) %></li>
  <% end %>
</ul>

<%= link_to 'Add a new cocktail', new_cocktail_path  %>

</div>

app/views/cocktails/new.html.erb
<h1>Add your fave cocktail:</h1>

<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>

<h2>Doses:</h2>
<ul>
  <% @cocktail.doses.each do |dose| %>
  <li><%= dose.description %> <%= dose.ingredient.name %></li>
  <% end %>
</ul>

<%= link_to 'Add dose', new_cocktail_dose_path(@cocktail)  %>

<%= link_to 'All cocktails', cocktails_path %>

app/views/cocktails/update.html.erb
<h1>Cocktails#update</h1>
<p>Find me in app/views/cocktails/update.html.erb</p>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/delete.html.erb
<h1>Doses#delete</h1>
<p>Find me in app/views/doses/delete.html.erb</p>

app/views/doses/edit.html.erb
<h1>Doses#edit</h1>
<p>Find me in app/views/doses/edit.html.erb</p>

app/views/doses/index.html.erb
<h1>Doses#index</h1>
<p>Find me in app/views/doses/index.html.erb</p>

app/views/doses/new.html.erb
<h1>Add yo dose for <%= @cocktail.name %></h1>

<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit %>
<% end %>

app/views/doses/show.html.erb
<h1>Doses#show</h1>
<p>Find me in app/views/doses/show.html.erb</p>

app/views/doses/update.html.erb
<h1>Doses#update</h1>
<p>Find me in app/views/doses/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>